;;; smalltalk-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gst-mode.el

(autoload 'gst "gst-mode" "\
Invoke GNU Smalltalk.

(fn COMMAND-LINE)" t)
(register-definition-prefixes "gst-mode" '("gst-" "send-to-smalltalk" "smalltalk-"))


;;; Generated autoloads from smalltalk-mode.el

(autoload 'smalltalk-mode "smalltalk-mode" "\
Major mode for editing Smalltalk code.

Commands:
\\{smalltalk-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.st\\'" . smalltalk-mode))
(add-to-list 'auto-mode-alist (cons "\\.star\\'" (catch 'archive-mode (dolist (mode-assoc auto-mode-alist 'archive-mode) (and (string-match (car mode-assoc) "Starfile.zip") (functionp (cdr mode-assoc)) (throw 'archive-mode (cdr mode-assoc)))))))
(add-to-list (if (boundp 'inhibit-local-variables-regexps) 'inhibit-local-variables-regexps 'inhibit-first-line-modes-regexp) "\\.star\\'")
(register-definition-prefixes "smalltalk-mode" '("smalltalk-"))

;;; End of scraped data

(provide 'smalltalk-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smalltalk-mode-autoloads.el ends here
